services:
  # Baza danych PostgreSQL
  - type: pserv
    name: beauty-salon-db
    env: postgres
    plan: free
    ipAllowList: [] # Dostęp z dowolnego IP

  # Backend
  - type: web
    name: wiktoria-beauty-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: beauty-salon-db
          property: connectionString

  # Frontend
  - type: web
    name: wiktoria-beauty-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production