services:
  # Baza danych PostgreSQL
  - type: postgres
    name: beauty-salon-db
    plan: free
    databaseName: beauty_salon
    user: beauty_user
    ipAllowList: []

  # Backend
  - type: web
    name: wiktoria-beauty-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: beauty-salon-db
          property: connectionString

  # Frontend
  - type: web
    name: wiktoria-beauty-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: https://wiktoria-beauty-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache